### ISSUE TITLE
How to connect Zimbra Admin console from php web application?

### ISSUE THREAD

**Issue by kstestuser** [libersoft/zcs-php#11]
Is there any reference for connecting and perform operations of create users for Linux Zimbra server from PHP or CakePHP application?
Here is the error page link : https://docs.google.com/file/d/0Bx5nzfr3qxekbjBXZF94clEwV3M/edit?usp=drivesdk

Can any body help me to how to resolve this issue ?

**Comment by gionn** [comment]
What is mails.mytestingserver.com?

**Comment by kstestuser** [comment]
Hi gionn 

I am testing zimbra server.
I have details of zimbra server ZIMBRA_LOGIN, ZIMBRA_PASS, ZIMBRA_SERVER, ZIMBRA_PORT
As in script showing on url below : 
Url : https://github.com/libersoft/zcs-php

// i have defined as its documented in above url
define('ZIMBRA_LOGIN', 'foo');
define('ZIMBRA_PASS',  'bar');
define('ZIMBRA_SERVER', 'zcs.example.com');
define('ZIMBRA_PORT', '7071');

I have fill my login details, but it respond me back with this error.
i unable to find where did i mistake, it only gives me this error https://docs.google.com/file/d/0Bx5nzfr3qxekbjBXZF94clEwV3M/edit?usp=drivesdk you saw.
Can you please tell me how to use the zcs-php library for php website so that i can access my zimbra server on my website.
Thanks & Regards
Karamjeet Singh

**Comment by gionn** [comment]
You have entered a ZIMBRA_SERVER parameter that is not valid, it looks like that mails.mytestingserver.com is not a proper DNS entry pointing to the zimbra server.

You can try using the IP address of the zimbra server, however a mail server is not going to work at all without a DNS properly configured, take a look to the Zimbra documentation for the prerequisites for getting it to work.

**Comment by kstestuser** [comment]
Thanks gionn 
Thanks for your time
Can you please provide me the reference for that (Zimbra documentation for the prerequisites) ?

**Comment by gionn** [comment]
https://www.zimbra.com/documentation/zimbra-collaboration-open-source

Good luck.

**Comment by kstestuser** [comment]
Hi Gionn 

I have not get fixed the issue given above, after tried to change domain authentication.

Please provide any idea how to fix "Host Refused" Issue.

Thanks
