### ISSUE TITLE
PSR-0 compliant autoloading

### ISSUE THREAD

**Issue by chrisramakers** [libersoft/zcs-php#4]
Do you have any plans on supporting the PSR-0 autoloading mechanism defined by the fig standards? This would make using the library in Symfony, ZF2 and other libraries a breeze and also would allow this library to be included in composer as a dependency.

I'm planning on integrating your library so maybe i'll have a look and see if I can refactor it so the API remains but the library becomes PSR-0 compatible.

More info: https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-0.md

**Comment by gionn** [comment]
We would definitively love PSR-0 support!

**Comment by chrisramakers** [comment]
Do you need to meet any hard PHP requirements? Else i'd look into using php5.3 namespaces in one go.

**Comment by malteo** [comment]
PHP 5.3 is fine

**Comment by malteo** [comment]
Thank you Chris!
